### PR TITLE
Fix support of bool

### LINKED ISSUE #647: Removal of support for bool?
**Describe the bug**
When trying to store a bool with:
```c++
bool on = true;
HighFive::Group group = h5_file.createGroup(name, true);
HighFive::Attribute reads_a = group.createAttribute<bool>("is_on", HighFive::DataSpace::From(on);
```
Two compiler errors occur due to a static_assert added in v2.5.0

**To Reproduce**
Either see the following build:
- https://dev.azure.com/jlees/pp-sketchlib/_build/results?buildId=1357&view=logs&jobId=1ebc38c8-fade-5a89-24da-f796855a97f6
- https://dev.azure.com/jlees/2174951b-ba6e-477b-8ec9-f4735bc1e2ba/_apis/build/builds/1357/logs/10

1. Go to https://github.com/bacpop/pp-sketchlib/pull/84
2. Install `environment.yml` with conda
3. Run `python setup.py build`

**Expected behavior**
Build without failure, no `static_assert` issue

**Stacktrace**
The following compiler errors occur:
```
2022-11-11T12:29:34.2177653Z       /usr/share/miniconda/envs/pp_env/include/highfive/bits/../bits/H5Converter_misc.hpp:83:19: error: static assertion failed: Booleans are not supported yet.
2022-11-11T12:29:34.2178241Z          83 |     static_assert(!std::is_same<type, bool>::value, "Booleans are not supported yet.");
2022-11-11T12:29:34.2178658Z             |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-11-11T12:29:34.2179569Z       /usr/share/miniconda/envs/pp_env/include/highfive/bits/../bits/H5Converter_misc.hpp: In instantiation of ‘const hdf5_type* HighFive::details::Writer<T>::get_pointer() [with T = bool; HighFive::details::Writer<T>::hdf5_type = bool]’:
2022-11-11T12:29:34.2180635Z       /usr/share/miniconda/envs/pp_env/include/highfive/bits/H5Attribute_misc.hpp:116:5:   required from ‘void HighFive::Attribute::write(const T&) [with T = bool]’
2022-11-11T12:29:34.2181661Z       /usr/share/miniconda/envs/pp_env/include/highfive/bits/../bits/H5Converter_misc.hpp:647:29: error: void value not ignored as it ought to be
2022-11-11T12:29:34.2182092Z         647 |             return vec.data();
2022-11-11T12:29:34.2182347Z             |                             ^

2022-11-11T12:29:34.2185810Z       /usr/share/miniconda/envs/pp_env/include/highfive/bits/H5ReadWrite_misc.hpp:109:1: error: ‘HighFive::details::BufferInfo<T>::BufferInfo(const HighFive::DataType&, F, HighFive::details::BufferInfo<T>::Operation) [with F = HighFive::Attribute::read(T&) const [with T = bool]::<lambda()>; T = bool]’, declared using local type ‘HighFive::Attribute::read(T&) const [with T = bool]::<lambda()>’, is used but never defined [-fpermissive]
2022-11-11T12:29:34.2186910Z         109 | BufferInfo<T>::BufferInfo(const DataType& dtype, F getName, Operation _op)
2022-11-11T12:29:34.2187265Z             | ^~~~~~~~~~~~~
```

**Desktop (please complete the following information):**
 - OS: ubuntu 20.10
 - Version: HighFive v2.6.2

**Additional context**
This appears to be due to this `static_assert`: https://github.com/BlueBrain/HighFive/blob/master/include/highfive/bits/H5Converter_misc.hpp#L83

Which seems to have be introduced in:
https://github.com/BlueBrain/HighFive/pull/586

So I think this has effectively removed support for storing a single `bool`, and I don't see this deprecation in any of the release notes?
I see that there is discussion about `vector<bool>` not yet being supported, but it seems even a single `bool` has been removed, which is awkward for backwards compatibility.

I also see that https://github.com/BlueBrain/HighFive/pull/591 reported something similar.

### PR DESCRIPTION
**Pull request by alkino**
Fix #647

### CODE REVIEW

**Comment by alkino** [comment]
Of course don't merge this, let's discuss

**Review by matz-e — COMMENTED** [review]
Quick wording check

File: include/highfive/bits/H5Converter_misc.hpp [hunk 1]
```diff
@@ -291,17 +320,74 @@ struct inspector<std::vector<T>> {
...
+        for (size_t i = 0; i < val.size(); ++i) {
+            m[i] = val[i] ? 1 : 0;
+        }
+    }
+
+    static void unserialize(const hdf5_type* vec_align,
+                            const std::vector<size_t>& dims,
+                            type& val) {
+        for (size_t i = 0; i < dims[0]; ++i) {
+            val[i] = vec_align[i] == 1 ? true : false;
```
Comment (1uc) [inline include/highfive/bits/H5Converter_misc.hpp:375]: This is subtly different from the standard conversion of integers to `bool`. As an example `2` is normally considered `true`. Here it would be considered `false`. This doesn't matter if people are reading files written by `HighFive`; but it might matter if they read back something that only follows the standard convention (and somehow contains some values that are neither `0` or `1`).

I think HDF5 conversion logic is rather permissive, i.e. it'll happily perform lossy conversion, when converting, say, `double` to `int`. For that reason it might be nice allow the conventional lossy conversion to `bool`.

Comment (alkino) [reply include/highfive/bits/H5Converter_misc.hpp]: I replaced `== 1` with `!= 0`

**Review by 1uc — APPROVED** [review]
Very nice work!
