### PR TITLE
Fix : Add support for std::byte as Dataset type for c++17 and above

### LINKED ISSUE #480: Add support for std::byte as Dataset type
Creating a dataset with underlying type of `std::byte` currently triggers a static assertion ("Type not supported"). This makes sense as `std::byte` is implemented as an enum rather than a scalar/numeric type. However, CPP Core Guidelines encourages the use of `std::byte` as the preferred way to refer to generic, non-character data. Does it make sense for `HighFive` to support this?

Minimal example of the issue:
```c++
#include <highfive/H5File.hpp>
#include <cstddef>
#include <vector>

using namespace HighFive;

int main()
{
    std::vector<std::byte> buffer(1024, std::byte(0xCD));
    File file("database.h5", File::ReadWrite | File::Create | File::Truncate);
    file.createDataSet<std::byte>("frame", DataSpace::From(buffer)).write(buffer);
}
```

### PR DESCRIPTION
**Pull request by WeinaJi**
**Description**
Add  support for std::byte as Dataset type when using c++17 and above 
- [x] Issue 1 fixed
- [x] Feature 1 added

Fixes #480 

**How to test this?**

```bash
cmake -DCMAKE_CXX_STANDARD=17 ..
make -j8
make test
```

**Test System**
 - OS: [e.g. Ubuntu 20.04]
 - Compiler: [e.g. clang 12.0.0]
 - Dependency versions: [e.g. hdf5 1.12]

### CODE REVIEW

**Review by alkino — APPROVED** [review]

File: tests/unit/test_all_types.cpp [hunk 1]
```diff
@@ -179,3 +179,34 @@ TEMPLATE_TEST_CASE("Scalar in std::vector<std::array>", "[Types]", bool, std::st
...
+    const std::string DATASET_NAME("dset");
+    TestType t1(5, std::byte(0xCD));
+
+    {
+        // Create a new file using the default property lists.
+        File file(FILE_NAME, File::ReadWrite | File::Create | File::Truncate);
+
+        // Create the dataset
+        DataSet dataset = file.createDataSet(
+            DATASET_NAME, {5}, create_datatype<typename details::inspector<TestType>::base_type>());
```
Comment (1uc) [inline tests/unit/test_all_types.cpp:195]: Here a `create_datatype<std::byte>` might be preferable, because it would be closer to what users are expected to write. The concern is that a bug in `details::inspector<TestType>::base_type` might hide other bugs, e.g. the code would work with `create_type<int>` but not `create_datatype<std::byte>`.

File: tests/unit/test_all_types.cpp [hunk 2]
```diff
@@ -179,3 +179,34 @@ TEMPLATE_TEST_CASE("Scalar in std::vector<std::array>", "[Types]", bool, std::st
...
+
+        // Write into the initial part of the dataset
+        dataset.write(t1);
```
Comment (1uc) [inline tests/unit/test_all_types.cpp:198]: Despite the above tests not doing it, it might be nice to also check:
```
        auto dataset2 = file.createDataSet(DATASET_NAME2, t1);
```


We could leave this for when we refactor the whole file to be more DRY.

**Review by 1uc — APPROVED** [review]
Many thanks!

File: tests/unit/test_all_types.cpp (hunk 1 above)
Comment (WeinaJi) [reply tests/unit/test_all_types.cpp]: Thanks for the comment, I've made the change.

File: tests/unit/test_all_types.cpp (hunk 2 above)
Comment (WeinaJi) [reply tests/unit/test_all_types.cpp:197]: ok, I leave this for the refactoring later.

**Review by 1uc — APPROVED** [review]
