### PR TITLE
Fix MSVC warnings

### LINKED ISSUE #164: Compiler warnings implicit type casts
Hi

Thanks a lot for your great efforts, they make working with HDF5 much easier! And your unit tests are a great tutorial :-)

When compiling with MSVS we get some warnings, mainly due to type conversions. Could you please fix those?

cheers, Marco

h5attribute_misc.hpp:37, MSBuild, Priority: Normal
'return': conversion from 'hsize_t' to 'size_t', possible loss of data

h5dataset_misc.hpp:37, MSBuild, Priority: Normal
'return': conversion from 'hsize_t' to 'size_t', possible loss of data

h5dataset_misc.hpp:63, MSBuild, Priority: Normal
'return': conversion from 'haddr_t' to 'size_t', possible loss of data

h5dataspace_misc.hpp:125, MSBuild, Priority: Normal
'static_cast': truncation of constant value

h5propertylist_misc.hpp:57, MSBuild, Priority: Normal
unreachable code

h5propertylist_misc.hpp:120, MSBuild, Priority: Normal
'argument': conversion from 'size_t' to 'int', possible loss of data

h5propertylist.hpp:153, MSBuild, Priority: Normal
'initializing': conversion from 'size_t' to 'const unsigned int', possible loss of data

### PR DESCRIPTION
**Pull request by tklauser**
This fixes all remaining MSVC type conversion warnings (both x64 and x32
build) and one "code unreachable" warning (by marking
HDF5ErrMapper::ToException as [[noreturn]]).
    
Also, in DataSpace::getMaxDimensions it fixes the H5S_UNLIMITED ->
DataSpace::UNLIMITED replacement to work on the correct vector.
    
Fixes #164

### CODE REVIEW

**Comment by tklauser** [comment]
This doesn't fix all warnings from #164 yet. I'll send an updated PR soon.

**Comment by tklauser** [comment]
Now updated to fix all warnings on x32/x64 msvc builds.

**Comment by emmenlau** [comment]
I can confirm that some of these issues are also found with gcc on the i686 platform. Thumbs up from me for this PR.

**Comment by tklauser** [comment]
@ferdonline Thanks for the feedback.

I updated the PR to use `hsize_t` as the return type for `Attribute::getStorageSize` and `DataSet::getStorageSize` and `haddr_t` for `DataSet::getOffset`. I'm not sure if this is what you intended? It would also be an API (ABI?) change as far as I can tell. Is this OK for you?

**Comment by tklauser** [comment]
Now updated and merged with the fixes provided by @ferdonline in tklauser/highfive#1

File: include/highfive/bits/H5Converter_misc.hpp [hunk 1]
```diff
@@ -46,7 +46,7 @@ inline bool is_1D(const std::vector<size_t>& dims)
 
 inline size_t compute_total_size(const std::vector<size_t>& dims)
 {
-    return std::accumulate(dims.begin(), dims.end(), static_cast<size_t>(1),
```
Comment (tklauser) [inline include/highfive/bits/H5Converter_misc.hpp]: It looks like the cast here is needed, otherwise we still get a warning when compiling on win32, where `size_t` > `unsigned int`. I'll send a follow-up PR.

Comment (tklauser) [reply include/highfive/bits/H5Converter_misc.hpp]: Send #179 to fix it, please have a look.
