### PR TITLE
Dont rely on exception in node.exist

### LINKED ISSUE #289: MSVC: Exception Trigger
One last mention about this #224 bug:

I know that MSVC compiler can be picky sometimes, but here is just a little help about how/where can you find this bug, ok?

When I run my application in:
 * Release mode: I got **no** exceptions at all.
 * Debug mode **without breakpoint** in any HighFive API lines: I got **no** exceptions too. All working good!

The only case that I got this exception above is when I ran my application in debug mode and **set some breakpoint** before same HighFive API command and then **I hit F10** to execute the app line by line.

In this case I got this exception below:

image

Can be here executing this:
```
bool exists = outputFile.exist(group_path);
```

And can be here too:
```
H5Easy::DataSet ds = H5Easy::dump(outputFile, full_path, my_vector, H5Easy::DumpMode::Overwrite);
```
Obs.: The exactly same source-code **runs perfect in Linux (g++).**

**My Setup:**
 * Windows 10 x64
 * Qt Creator IDE 5.11.1
 * Qt version 5.14.1
 * Compiler: MSVC 2019

### PR DESCRIPTION
**Pull request by ferdonline**
The implementation of `Node.exist()` required catching an exception that we generated ourselves. Despite being a simple principle, it kind of used exceptions for flow control and In some compiler toolchains (QT) this would create unwanted error messages (#224, #289)

## This PR
Makes the low-level `_exist` function conditionally treat the error as a normal false, not throwing exception. This design even simplified the implementation of the public `exist()` method.

Fixes #289

### CODE REVIEW

File: include/highfive/bits/H5Node_traits_misc.hpp [hunk 1]
```diff
@@ -205,12 +206,8 @@ inline bool NodeTraits<Derivate>::exist(const std::string& group_path) const {
...
     if (group_path.find('/') != std::string::npos) {
         _exist("/");  // Shall not throw under normal circumstances
-        try {
-            SilenceHDF5 silencer;
-            return _exist(group_path);
-        } catch (const GroupException&) {
-            return false;
-        }
+        // Unless "/" (already checked), verify path exists (not thowing errors)
+        return (group_path == "/")? true : _exist(group_path, false);
```
Comment (alexsavulescu) [inline include/highfive/bits/H5Node_traits_misc.hpp]: White space between ")" and "?" :)

**Comment by ferdonline** [comment]
@alexsavulescu sorry, github always dimisses even on small changes. I dont intend to change more
